### ISSUE TITLE
정적 분석 리포트를 공유

### ISSUE THREAD

**Issue by DWL5** [woowacourse-teams/2021-tyf#227]
- 소나큐브

**Comment by Be-poz** [comment]
https://github.com/Be-poz/TIL/blob/master/Infra/%EA%B0%84%EB%9E%B5%ED%9E%88%EB%B3%B4%EB%8A%94%20SonarQube%EC%99%80%20Jenkins%20%EC%97%B0%EB%8F%99%ED%95%98%EA%B8%B0.md
