### ISSUE TITLE
정산 플로우 리팩토링

### ISSUE THREAD

**Issue by Rok93** [woowacourse-teams/2021-tyf#265]
- 로그인 - 어드민 페이지 접속 API
    - 서브모듈에 등록한 임의값과 비교
    - 토큰

정산등록 되었는지 필드: `isBankRegistered` (boolean)
1. members/{pageName} 에 `isBankRegistered` 필드 추가 (O)
2. donation시 정산가능계정 등록여부 validation 추가 (X) 
    - 해당 기능은 지금 만들기에는 문제가 많다.
    - 일단 기존 테스트가 다 깨짐 (Donation, Payment, Member  AcceptanceTest 깨짐!)
    - Service단도 하나 깨지지만,
    - 특히 인수테스트 쪽은 답이 없음 (계좌 등록 승인(?)해주는 API를 만들어야 함)
3. /members/me/에 `isBankRegistered` 추가하여, 정산가능계정인지 확인해서 정산관리url이 담긴 popup / snackbar로 알람 (O)
- /members/me/account는 정산 페이지에서 계좌정보 그릴 때 호출

**Comment by DWL5** [comment]
방금 확인했는데 테스트 다 잘돌아가!
로컬로 서버 돌리고 테스트 돌리면 깨지더라..
