### ISSUE TITLE
후원완료후 후원목록 리랜더링

### ISSUE THREAD

**Issue by hchayan** [woowacourse-teams/2021-tyf#278]
후원완료후 기존 후원페이지에서 후원목록이 리렌더링 되지 않는다.

**Comment by jho2301** [comment]
이거는 기존 흐름에서 처리못할거같은데 소켓같은걸로 신호받아야하는거아니야?

**Comment by hchayan** [comment]
> 이거는 기존 흐름에서 처리못할거같은데 소켓같은걸로 신호받아야하는거아니야?

그래도 나중에 처리해야될꺼같아서 등록해봤어

**Comment by jho2301** [comment]
추후 리액트쿼리를 적용하거나 브라우저 포커스시 fetch하도록 알아보기
