### ISSUE TITLE
도네이션 실패 메시지를 구체화한다.

### ISSUE THREAD

**Issue by Joyykim** [woowacourse-teams/2021-tyf#355]
충전금액 없을때 도네이션시 실패 메시지가 더 구체적일 필요가 있다.

<img width="455" alt="KakaoTalk_Image_2021-09-23-12-32-29" src="https://user-images.githubusercontent.com/56679885/134451028-7f5a1fde-74b1-4632-a85a-7b0d580a7525.png">

**Comment by jho2301** [comment]
에러메시지 구체화 커밋 머지완료우
