### ISSUE TITLE
도네이션 메세지 등록 API, name 프로퍼티 제거

### ISSUE THREAD

**Issue by jho2301** [woowacourse-teams/2021-tyf#385]
- 관련 유효성 검사 로직 제거
- 클라이언트도 서버 API 변경에 따라 페이로드 변경

**Comment by Be-poz** [comment]
![image](https://user-images.githubusercontent.com/45073750/135594656-54a1a6ea-bfc1-4794-87ef-e0fa7293ea95.png)

**Comment by Be-poz** [comment]
메세지 보내는 api request 스펙에서 name이 빠졌습니돠

**Comment by Be-poz** [comment]
![image](https://user-images.githubusercontent.com/45073750/135607205-ae55c2c6-10e0-4f84-bfea-a4646fe4704c.png)
![image](https://user-images.githubusercontent.com/45073750/135607209-7b57c556-59a9-4458-a93a-2fbc6b3a430e.png)
![image](https://user-images.githubusercontent.com/45073750/135607241-02146c39-7397-4c29-9925-c0825479f2a7.png)
해당 API Response에 ``pageName`` 이 추가됐어~!
