### ISSUE TITLE
외부API 호출을 트랜잭션 바깥에서 하도록 변경한다

### ISSUE THREAD

**Issue by Joyykim** [woowacourse-teams/2021-tyf#537]
현재는 트랜잭션 내부(서비스 레이어)에서 외부API 호출중.
외부API응답시간이 길어지면  트랜잭션이 길어지면서 성능 저하, DB타임아웃과 같은 이슈가 발생할 수 있음.

**Comment by DWL5** [comment]
이거는 RestTemplate를 WebClient로 변경해보는 건 어떤가요?
http://egloos.zum.com/preludeb/v/7466753
